name: Submit Form Data

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User Name'
        required: true
        type: string
      phone:
        description: 'Phone Number'
        required: true
        type: string
      guests:
        description: 'Number of Guests'
        required: true
        type: string

jobs:
  submitFormData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "YourName"

      - name: Create response file and push data
        run: |
          echo "Name: ${{ github.event.inputs.name }}" >> data/responses.csv
          echo "Phone: ${{ github.event.inputs.phone }}" >> data/responses.csv
          echo "Guests: ${{ github.event.inputs.guests }}" >> data/responses.csv
          
          git add data/responses.csv
          git commit -m "Add form response"
          git push
