name: Submit Form Data

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User Name'
        required: true
        type: string
      phone:
        description: 'Phone Number'
        required: true
        type: string
      guests:
        description: 'Number of Guests'
        required: true
        type: string

jobs:
  submitFormData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "chrismaje63@gmail.com"
          git config --global user.name "chrismat-05"

      - name: Create response file and push data
        run: |
          mkdir -p data # Ensure the 'data' folder exists
          echo "Name: ${{ github.event.inputs.name }}" >> data/responses.csv
          echo "Phone: ${{ github.event.inputs.phone }}" >> data/responses.csv
          echo "Guests: ${{ github.event.inputs.guests }}" >> data/responses.csv
          echo "" >> data/responses.csv # Add a blank line for readability

          git add data/responses.csv
          git commit -m "Add form response"
          git push https://x-access-token:${{ secrets.form_animated }}@github.com/chrismat-05/animated_form.git HEAD:main
