name: Submit Form Data

on:
  push:
    branches:
      - main

jobs:
  submitFormData:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git configuration
      - name: Set up Git configuration
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "YourName"

      # Create response file and push data
      - name: Create response file and push data
        run: |
          echo "Name: ${{ secrets.form_cma }}" >> responses.csv
          echo "Phone: ${{ secrets.FORM_PHONE }}" >> responses.csv
          echo "Guests: ${{ secrets.FORM_GUESTS }}" >> responses.csv

          git add responses.csv
          git commit -m "Add form response"
          git push
        env:
          FORM_PHONE: ${{ secrets.FORM_PHONE }} # Example secret for phone
          FORM_GUESTS: ${{ secrets.FORM_GUESTS }} # Example secret for guests
